version: "3.7"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  # pgadmin:
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: postgres@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: postgres
  #   ports:
  #     - "5433:80"
  #   volumes:
  #     - ./pgadmin-data:/var/lib/pgadmin